---
language: go
sudo: required

services:
    - docker

go:
    - "1.10.3"

go_import_path: gopkg.in/goracle.v2

addons:
    apt:
        packages:
            - libaio1

env:
    global:
        - GORACLE_DRV_TEST_USERNAME=test
        - GORACLE_DRV_TEST_PASSWORD=test
        - GORACLE_DRV_TEST_DB=oracle.gthomas.eu:49161/xe
        - ORACLE_INSTANTCLIENT_MAJOR=12.2
        - ORACLE_INSTANTCLIENT_VERSION=12.2.0.1.0
        - ORACLE=/usr/local/oracle
        - ORACLE_HOME=$ORACLE/lib/oracle/$ORACLE_INSTANTCLIENT_MAJOR/client64
        - LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$ORACLE_HOME/lib
        - C_INCLUDE_PATH=$C_INCLUDE_PATH:$ORACLE/include/oracle/$ORACLE_INSTANTCLIENT_MAJOR/client64

# copied from https://github.com/sergeymakinen/docker-oracle-instant-client/blob/master/12.2/Dockerfile
before_install:
    - export CGO_CFLAGS=-I/usr/include/oracle/12.2/client64
    - export CGO_LDFLAGS=-L/usr/lib/oracle/12.2/client64/lib
    - apt-get update && apt-get install -y libaio1 \
        curl rpm2cpio cpio \
        && mkdir $ORACLE && TMP_DIR="$(mktemp -d)" && cd "$TMP_DIR" \
        && curl -L https://github.com/sergeymakinen/docker-oracle-instant-client/raw/assets/oracle-instantclient$ORACLE_INSTANTCLIENT_MAJOR-basic-$ORACLE_INSTANTCLIENT_VERSION-1.x86_64.rpm -o basic.rpm \
        && rpm2cpio basic.rpm | cpio -i -d -v && cp -r usr/* $ORACLE && rm -rf ./* \
        && ln -s libclntsh.so.12.1 $ORACLE/lib/oracle/$ORACLE_INSTANTCLIENT_MAJOR/client64/lib/libclntsh.so.$ORACLE_INSTANTCLIENT_MAJOR \
        && ln -s libocci.so.12.1 $ORACLE/lib/oracle/$ORACLE_INSTANTCLIENT_MAJOR/client64/lib/libocci.so.$ORACLE_INSTANTCLIENT_MAJOR \
        && curl -L https://github.com/sergeymakinen/docker-oracle-instant-client/raw/assets/oracle-instantclient$ORACLE_INSTANTCLIENT_MAJOR-devel-$ORACLE_INSTANTCLIENT_VERSION-1.x86_64.rpm -o devel.rpm \
        && rpm2cpio devel.rpm | cpio -i -d -v && cp -r usr/* $ORACLE && rm -rf "$TMP_DIR" \
        && echo "$ORACLE_HOME/lib" > /etc/ld.so.conf.d/oracle.conf && chmod o+r /etc/ld.so.conf.d/oracle.conf && ldconfig \
        && rm -rf /var/lib/apt/lists/* && apt-get purge -y --auto-remove curl rpm2cpio cpio

install:
    - go get -t .

script:
    - go test -coverprofile=coverage.txt -covermode=atomic .

after_success:
    - bash <(curl -s https://codecov.io/bash)
