---
language: go
sudo: required

services:
    - docker

go:
    - "1.10.3"

go_import_path: gopkg.in/goracle.v2

before_install:
    - docker pull sath89/oracle-12c
    - docker pull sergeymakinen/oracle-instant-client:12.2

install:
    - go get -t .

script:
    - docker run -d -p 1521:1521 sath89/oracle-12c
    - go test -c -covermode=atomic .
    - while ! nc -z localhost 1521; do echo 'waiting for DB'; sleep 5; done
    - docker run -ti --rm
        -e GORACLE_DRV_TEST_USERNAME=system
        -e GORACLE_DRV_TEST_PASSWORD=oracle
        -e GORACLE_DRV_TEST_DB=localhost:1521/xe
        -v $(pwd)/goracle.v2.test:/goracle.v2.test:ro
        sergeymakinen/oracle-instant-client:12.2
        /goracle.v2.test -test.coverprofile=coverage.txt

after_success:
    - bash <(curl -s https://codecov.io/bash)

# vim: set et:
