# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12.9

    environment:
      GO111MODULE: "on"
      GORACLE_DRV_TEST_USERNAME: test
      GORACLE_DRV_TEST_PASSWORD: test
      GORACLE_DRV_TEST_DB: oracle.gthomas.eu:49161/se.oracle.gulacsi.eu

    working_directory: /go/src/gopkg.in/goracle.v2

    steps:
      - run:
          name: Download Oracle Instant Client
          command: wget -O instantclient-basic-linux-x64.zip https://download.oracle.com/otn_software/linux/instantclient/193000/instantclient-basic-linux.x64-19.3.0.0.0dbru.zip

      - run:
          name: Unzip Oracle Instant Client
          command: sudo sh -c 'mkdir -p /usr/lib/oracle && unzip instantclient-basic-linux-x64.zip -d /usr/lib && ldconfig -v /usr/lib/oracle/instantclient_19_3'

      - checkout

      - run:
          name: Build test executable
          command: go test -c -covermode=atomic .

      - run:
          name: Run goracle.v2.test
          command: goracle.v2.test -test.coverprofile=coverage.txt -test.v

      - run:
          name: Upload coverage to codecov.io
          command: bash <(curl -s https://codecov.io/bash)
